# Generated by Django 4.1.7 on 2023-03-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='players',
            new_name='team_players',
        ),
        migrations.RemoveField(
            model_name='team',
            name='captain',
        ),
        migrations.RemoveField(
            model_name='team',
            name='club',
        ),
        migrations.AlterField(
            model_name='club',
            name='players',
            field=models.ManyToManyField(to='base.player'),
        ),
    ]
