# Generated by Django 4.1.7 on 2023-03-05 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_player_license'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player',
        ),
    ]
