# Generated by Django 4.1.7 on 2023-03-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_player_options_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(to='base.player'),
        ),
    ]
